import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import LayoutBase from "@/components/LayoutBase";
import ThemeRegistry from "@/components/ThemeRegistry";

import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Psicobank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
          <ThemeRegistry>
            <LayoutBase>{children}</LayoutBase>
          </ThemeRegistry>
      </body>
    </html>
  );
}
